first version of main page
meetjspl/abandoned_meetjs.pl pull request #1
Opened 2023-04-12 17:47 UTC by kamilsobik

Main setup:
- [ ] Main page 
- [ ] Navigation
- [ ] Example page

2023-04-13 11:08 UTC, mmiszy requested changes
Dodałem komentarze. Dodatkowo, chciałbym jeszcze:

- [x] dodać `prettier`
- [x] dodać `lint-staged`
- [x] dodać `husky`
- [x] usunąć `.next`
- [ ] sformatować wszystko przy pomocy `prettier --write .`

2023-04-13 11:08 UTC, typeofweb commented on .gitignore
> +node_modules
```suggestion
node_modules
.env
.env*.local
.idea
*.tsbuildinfo
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
.DS_Store
.next
```

2023-04-13 11:08 UTC, mmiszy commented on .next/app-build-manifest.json
> +{
Folder `.next` nie powinien być w repo

2023-04-13 11:08 UTC, mmiszy commented on .vscode/settings.json
> +}
Moja propozycja:

```suggestion
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "eslint.run": "onSave",
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
}
```

bo i tak dodamy prettiera.

2023-04-13 11:08 UTC, mmiszy commented on next.config.js
> +  },
```suggestion
  },
  reactStrictMode: true,
```

2023-04-13 11:08 UTC, typeofweb commented on tsconfig.json
> +    "target": "es5",
```suggestion
    "target": "es2022",
```

2023-04-13 11:08 UTC, mmiszy commented on app/globals.css
Proponowałbym od razu stworzyć folder `src` i przenieść do niego cały `app` tak, żeby pliki były w `src/app/…`.
To sprawi, że struktura będzie znacznie czytelniejsza i nie będzie tak wielu plików w głównym folderze.
Wtedy komponenty umieścimy w `src/components` albo `src/ui`, utilsy w `src/utils` i tak dalej.

2023-04-13 11:08 UTC, mmiszy commented on tsconfig.json
> +      "@/*": ["./*"]
Jeśli zaaplikujemy zmianę z folderem `src` o której pisałem wyżej, to tutaj też trzeba zmienić:
```suggestion
      "@/*": ["./src/*"]
```

2023-04-18 07:22 UTC, kamilsobik commented on .gitignore
> +node_modules
done 👌

2023-04-18 07:25 UTC, kamilsobik commented on .next/app-build-manifest.json
> +{
deleted ✂️

2023-04-18 08:34 UTC, kamilsobik commented on app/globals.css
zrobione 👌

2023-04-18 10:13 UTC, mmiszy commented
prettier, husky i lint-staged jeszcze trzeba skonfigurować :) Mogę z tym pomóc:
https://github.com/typeofweb/devfaq/tree/7c98b84db642c8810bf600edd96caf5addf9767a/.husky
https://github.com/typeofweb/devfaq/blob/7c98b84db642c8810bf600edd96caf5addf9767a/prettier.config.js
https://github.com/saleor/saleor-app-payment-adyen/blob/7ad068f76ae5634ca89c314fcae6a6dbec58e920/.lintstagedrc.js

2023-04-19 12:02 UTC, Rxbsxn commented on package.json
@kamilsobik te wcięcia są tutaj okej?

2023-04-19 12:17 UTC, mmiszy approved these changes

2023-04-19 12:17 UTC, merged