Social media buttons
meetjspl/abandoned_meetjs.pl pull request #12
Opened 2023-04-27 17:29 UTC by Jakub09

2023-04-27 20:09 UTC, mmiszy commented
Musisz zrobić `git pull origin main`

2023-05-24 09:16 UTC, mmiszy requested changes

2023-05-24 09:16 UTC, mmiszy commented on src/app/components/Button.tsx
> +const defaultStyles = " cursor-pointer m-10 w-60 px-9  py-5 text-2xl ";
```suggestion
const defaultStyles = "cursor-pointer m-10 w-60 px-9  py-5 text-2xl";
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/components/Button.tsx
> +	pill: "rounded-full ",
```suggestion
	pill: "rounded-full",
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/components/Logo.tsx
> +	);
```suggestion
	return <Image width={1280} height={400} src="../meetjs-logo.svg" alt={""} />;
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/globals.css
> +}
Tych stylów nie powinno tu być jeśli używamy Tailwinda.

2023-05-24 09:16 UTC, mmiszy commented on src/app/globals.css
> +	--text-color-white-rgb: #fff;
Oprócz tego, kolory trzeba dodać też do `tailwind.config.js` – wtedy będą dostępne wszędzie jako klasy.

2023-05-24 09:16 UTC, mmiszy commented on src/app/page.tsx
> +		</>
```suggestion
		<main className="flex min-h-screen flex-col items-center p-10 ">
			<Logo />
			<Link href="https://facebook.com/meetjspl/">
				<Button shape="pill" variant="social" className=" duration-300 ease-in hover:scale-110">
					<FaFacebook className="mb-1 mr-2 inline  " />
					Facebook
				</Button>
			</Link>
			<Link href="https://discord.gg/UycCSpRh6j">
				<Button shape="pill" variant="social" className=" duration-300 ease-in hover:scale-110">
					<FaDiscord className="mb-1 mr-2 inline " />
					Discord
				</Button>
			</Link>
			<Link href="https://summit.meetjs.pl/2023/">
				<Button shape="pill" variant="social" className=" duration-300 ease-in hover:scale-110">
					<CgWebsite className="mb-1 mr-2 inline " />
					Summit
				</Button>
			</Link>
		</main>
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/page.tsx
> +			<main className="flex min-h-screen flex-col items-center p-10 ">
```suggestion
			<main className="flex min-h-screen flex-col items-center p-10">
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/page.tsx
> +						<FaFacebook className="mb-1 mr-2 inline  " />
```suggestion
						<FaFacebook className="mb-1 mr-2 inline" />
```

2023-05-24 09:16 UTC, mmiszy commented on src/app/page.tsx
> +					<Button shape="pill" variant="social" className=" duration-300 ease-in hover:scale-110">
`button` nie może być w środku `<a>`

2023-05-24 09:16 UTC, mmiszy commented on tailwind.config.js
> +		"./src/app/**/*.{js,ts,jsx,tsx}",
Czemu?

2023-06-13 10:49 UTC, mmiszy requested changes

2023-06-13 10:49 UTC, mmiszy commented on src/app/page.tsx
> +					<Link href="/facebook">
<a> nie może być w <button> ani <button> w <a>. Nie ma to sensu – albo chcemy link, albo przycisk.
W tym przypadku chcemy link, który ma wyglądać jak przycisk.

2023-06-29 09:52 UTC, Jakub09 commented on src/app/components/ExternalLink.tsx
- Importuje tutaj style oraz warianty z buttona żeby komponent miał dostęp do nowych styli jeżeli powstaną. 
- ButtonStyleProps - pomysł był taki że jeżeli użytkownik przekaże button=true to komponent bedzie wymagał podania wariantu i kształtu.

2023-06-29 18:04 UTC, typeofweb approved these changes

2023-06-29 18:16 UTC, merged